In [1]:
import pandas as pd

In [2]:
data=pd.Series([0.5,1.2,3.6,5.6], index=['a','b','c','d'])
data


a    0.5
b    1.2
c    3.6
d    5.6
dtype: float64

In [3]:
data['a']

0.5

In [4]:
# we can even use noncontiguous or nonsequential
data=pd.Series([0.5,2.0,3.4,4.7],index=[2,3,7,1])
data

2    0.5
3    2.0
7    3.4
1    4.7
dtype: float64

In [5]:
data[1]

4.7

In [6]:
population_dict={'Hanoi': 12003000321,
                 'HoChiMinh': 15732193424
                 'HaiPhong': 29048321763
                 'DaNang': 17213532879
                }
population=pd.Series(population_dict)
population

SyntaxError: invalid syntax (<ipython-input-6-32262fd4dfe4>, line 3)

In [7]:
population_dict={'Hanoi': 12003000321,
                 'HoChiMinh': 15732193424,
                 'HaiPhong': 29048321763,
                 'DaNang': 17213532879
                }
population=pd.Series(population_dict)
population

Hanoi        12003000321
HoChiMinh    15732193424
HaiPhong     29048321763
DaNang       17213532879
dtype: int64

In [8]:
population['HoChiMinh']

15732193424

In [9]:
population['HaNoi':'HaiPhong']

KeyError: 'HaNoi'

In [10]:
population['Hanoi':'HaiPhong']

Hanoi        12003000321
HoChiMinh    15732193424
HaiPhong     29048321763
dtype: int64

In [11]:
pd.Series([2,5,6])

0    2
1    5
2    6
dtype: int64

In [12]:
pd.Series(5,index=[100,200,300])

100    5
200    5
300    5
dtype: int64

In [13]:
pd.Series(2:'a',1:'b',3:'c')

SyntaxError: invalid syntax (<ipython-input-13-5457dbbf678c>, line 1)

In [14]:
pd.Series({2:'a',1:'b',3:'c'})

2    a
1    b
3    c
dtype: object

In [15]:
pd.Series({2:'a',1:'b',3:'c'}, index=[3,2])

3    c
2    a
dtype: object

In [16]:
area_dict={'Hanoi': 12003000321,
                 'HoChiMinh': 15732193424,
                 'HaiPhong': 29048321763,
                 'DaNang': 17213532879}

In [17]:
area=pd.Series(area_dict)
area

Hanoi        12003000321
HoChiMinh    15732193424
HaiPhong     29048321763
DaNang       17213532879
dtype: int64

In [18]:
states=pd.DataFrame({'population': population,'area': area})
states

population         area
Hanoi      12003000321  12003000321
HoChiMinh  15732193424  15732193424
HaiPhong   29048321763  29048321763
DaNang     17213532879  17213532879

In [19]:
states.index

Index(['Hanoi', 'HoChiMinh', 'HaiPhong', 'DaNang'], dtype='object')

In [20]:
states.columns

Index(['population', 'area'], dtype='object')

In [21]:
states['area']

Hanoi        12003000321
HoChiMinh    15732193424
HaiPhong     29048321763
DaNang       17213532879
Name: area, dtype: int64

In [22]:
# DataFrame is a collection of Series object, and a single-column DataFrame can be contructed from a single Series

pd.DataFrame(population,columns=['population'])

population
Hanoi      12003000321
HoChiMinh  15732193424
HaiPhong   29048321763
DaNang     17213532879

In [23]:
data=[{'a':i,'b':2*i 
        for i in range(3)}]
pd.DataFrame(data)

SyntaxError: invalid syntax (<ipython-input-23-4c9f870f0786>, line 2)

In [24]:
data=[{'a':i,'b':2*i }
        for i in range(3)]
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [25]:
#missing some keyss , pandas will fill them in with NaN
pd.DataFrame([{'a':1,'b':2},{'b':3,'c':4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [26]:
ind=pd.Index([2,3,5,7,11])
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

In [27]:
ind[1]

3

In [28]:
ind[::2]

Int64Index([2, 5, 11], dtype='int64')

In [29]:
print(ind.shape,ind.size,ind.ndim,ind.dtype)

(5,) 5 1 int64


In [30]:
ind[1]=0

TypeError: Index does not support mutable operations

In [31]:
data=pd.Series([0.25,0.5,0.75], index=['a','b','c','d'])
data

ValueError: Length of passed values is 3, index implies 4.

In [32]:
data=pd.Series([0.25,0.5,0.75,1.5], index=['a','b','c','d'])
data

a    0.25
b    0.50
c    0.75
d    1.50
dtype: float64

In [33]:
data['b']

0.5

In [34]:
'a' in data

True

In [35]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [36]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.5)]

In [37]:
data['c']=6.0

In [38]:
data

a    0.25
b    0.50
c    6.00
d    1.50
dtype: float64

In [39]:
# slicing by explicit index
data['a':'c']

a    0.25
b    0.50
c    6.00
dtype: float64

In [40]:
data[0:2]

a    0.25
b    0.50
dtype: float64

In [41]:
#masking
data[data>0.3 & data<6.0]

TypeError: Cannot perform 'rand_' with a dtyped [float64] array and scalar of type [bool]

In [42]:
#masking
data[(data>0.3) & (data<6.0)]

b    0.5
d    1.5
dtype: float64

In [43]:
#fancy indexing
data['a','e']

ValueError: key of type tuple not found and not a MultiIndex

In [44]:
data[['a','e']]

KeyError: "Passing list-likes to .loc or [] with any missing labels is no longer supported. The following labels were missing: Index(['e'], dtype='object'). See https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike"

In [45]:
# loc, iloc, and ix

# slicing and indexing convention can be a source of confusion. 
data=pd.Series(['a','b','c'],index=[1,3,5])
data

1    a
3    b
5    c
dtype: object

In [46]:
# explicit index when indexing
data[1]

'a'

In [47]:
#implicit index when slicing
data[1:3]

3    b
5    c
dtype: object

In [48]:
# because of this pontential confusion in the case of interger indxes, Pandas provides some special indexer that explicitly expose certain indexing schemes.
# loc attribute allows indexing and slicing that always reference the explicit
data.loc[1]

'a'

In [49]:
data.loc[1:3]

1    a
3    b
dtype: object

In [50]:
data.iloc[1]

'b'

In [51]:
data.iloc[1:3]

3    b
5    c
dtype: object

In [52]:
area=pd.Series({'HaNoi': 32040, 'HoChiMinh': 78934,'DaNang':9873, 'HaiPhong':11201,'ThanhHoa':128654})
pop=pd.Series({'HaNoi': 10998832, 'HoChiMinh': 17893423,'DaNang':1987347, 'HaiPhong':1120142,'ThanhHoa':3865411})
data=pd.DataFrame('Area': area,'Population':pop)
data

SyntaxError: invalid syntax (<ipython-input-52-db7152a04634>, line 3)

In [53]:
area=pd.Series({'HaNoi': 32040, 'HoChiMinh': 78934,'DaNang':9873, 'HaiPhong':11201,'ThanhHoa':128654})
pop=pd.Series({'HaNoi': 10998832, 'HoChiMinh': 17893423,'DaNang':1987347, 'HaiPhong':1120142,'ThanhHoa':3865411})
data=pd.DataFrame({'Area': area,'Population':pop})
data

Area  Population
HaNoi       32040    10998832
HoChiMinh   78934    17893423
DaNang       9873     1987347
HaiPhong    11201     1120142
ThanhHoa   128654     3865411

In [54]:
data['Area']

HaNoi         32040
HoChiMinh     78934
DaNang         9873
HaiPhong      11201
ThanhHoa     128654
Name: Area, dtype: int64

In [55]:
data.Area

HaNoi         32040
HoChiMinh     78934
DaNang         9873
HaiPhong      11201
ThanhHoa     128654
Name: Area, dtype: int64

In [56]:
data.Population

HaNoi        10998832
HoChiMinh    17893423
DaNang        1987347
HaiPhong      1120142
ThanhHoa      3865411
Name: Population, dtype: int64

In [57]:
data.Area is data['Area']


True

In [58]:
data['density']=data['Population']/data['Area']
data


Area  Population     density
HaNoi       32040    10998832  343.284395
HoChiMinh   78934    17893423  226.688411
DaNang       9873     1987347  201.291097
HaiPhong    11201     1120142  100.003750
ThanhHoa   128654     3865411   30.045012

In [59]:
data.values

array([[3.20400000e+04, 1.09988320e+07, 3.43284395e+02],
       [7.89340000e+04, 1.78934230e+07, 2.26688411e+02],
       [9.87300000e+03, 1.98734700e+06, 2.01291097e+02],
       [1.12010000e+04, 1.12014200e+06, 1.00003750e+02],
       [1.28654000e+05, 3.86541100e+06, 3.00450122e+01]])

In [60]:
data.T

HaNoi     HoChiMinh        DaNang      HaiPhong  \
Area        3.204000e+04  7.893400e+04  9.873000e+03  1.120100e+04   
Population  1.099883e+07  1.789342e+07  1.987347e+06  1.120142e+06   
density     3.432844e+02  2.266884e+02  2.012911e+02  1.000037e+02   

                ThanhHoa  
Area        1.286540e+05  
Population  3.865411e+06  
density     3.004501e+01

In [61]:
data.values[0]

array([3.20400000e+04, 1.09988320e+07, 3.43284395e+02])

In [62]:
data['Area']

HaNoi         32040
HoChiMinh     78934
DaNang         9873
HaiPhong      11201
ThanhHoa     128654
Name: Area, dtype: int64

In [63]:
data.iloc[:3,:2]

Area  Population
HaNoi      32040    10998832
HoChiMinh  78934    17893423
DaNang      9873     1987347

In [64]:
dataloc[:'HoChiMinh',:'Population']

NameError: name 'dataloc' is not defined

In [65]:
data.loc[:'HoChiMinh',:'Population']

Area  Population
HaNoi      32040    10998832
HoChiMinh  78934    17893423

In [66]:
data.ix[:3,:'Population']

AttributeError: 'DataFrame' object has no attribute 'ix'

In [67]:
data.loc[data.density>100, ['Population','density']]

Population     density
HaNoi        10998832  343.284395
HoChiMinh    17893423  226.688411
DaNang        1987347  201.291097
HaiPhong      1120142  100.003750

In [68]:
# Unfuncs: Index preservation

import pandas as pd
import numpy as np


In [69]:
rng=np.random.RandomState(42)
ser=pd.Series(rng.randint(0,10,4))
ser

0    6
1    3
2    7
3    4
dtype: int32

In [70]:
rng

RandomState(MT19937) at 0x1CC10668BF8

In [71]:
df=pd.DataFrame(rng.randint(0,10,(3,4)), columns=['A','B','C','D'])
df

A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [72]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [73]:
np.sin(df*np.pi/4)

A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

In [74]:
area=pd.Series({'HaNoi': 32040, 'HoChiMinh': 78934,'DaNang':9873, 'HaiPhong':11201,'ThanhHoa':128654}, name='Area')
population=pd.Series({'HaNoi': 10998832, 'HoChiMinh': 17893423,'DaNang':1987347, 'HaiPhong':1120142,'ThanhHoa':3865411}, name='population')
density=population/area

In [75]:
density

HaNoi        343.284395
HoChiMinh    226.688411
DaNang       201.291097
HaiPhong     100.003750
ThanhHoa      30.045012
dtype: float64

In [76]:
area=pd.Series({'HaNoi': 32040, 'HoChiMinh': 78934,'DaNang':9873, 'HaiPhong':11201,'ThanhHoa':128654}, name='Area')
population=pd.Series({'HoChiMinh': 17893423,'DaNang':1987347, 'HaiPhong':1120142,'ThanhHoa':3865411}, name='population')
population/area

DaNang       201.291097
HaNoi               NaN
HaiPhong     100.003750
HoChiMinh    226.688411
ThanhHoa      30.045012
dtype: float64

In [77]:
area.index|population.index

Index(['DaNang', 'HaNoi', 'HaiPhong', 'HoChiMinh', 'ThanhHoa'], dtype='object')

In [78]:
A=pd.Series([2,4,6], index=[0,1,2])
B=pd.Series([1,3,5], index=[1,2,3])
A+B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [79]:
A

0    2
1    4
2    6
dtype: int64

In [80]:
B

1    1
2    3
3    5
dtype: int64

In [81]:
A.add(B)

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [82]:
A.add(B,fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [83]:
#Index alighment in DataFrame
A=pd.DataFrame(rng.randint(0,20,(2,2)), columns=list('AB'))
A

A   B
0  1  11
1  5   1

In [84]:
B=pd.DataFrame(rng.randint(0,10,(3,3)), columns=list('BAC'))

In [85]:
B

B  A  C
0  4  0  9
1  5  8  0
2  9  2  6

In [86]:
A+B

A     B   C
0   1.0  15.0 NaN
1  13.0   6.0 NaN
2   NaN   NaN NaN

In [87]:
fill=A.stack().mean()
A.add(B,fill_value=fill)

A     B     C
0   1.0  15.0  13.5
1  13.0   6.0   4.5
2   6.5  13.5  10.5

In [88]:
# Unfuncs: Operation between dataframe and series
A=rng.randint(10,size=(3,4))
A

array([[3, 8, 2, 4],
       [2, 6, 4, 8],
       [6, 1, 3, 8]])

In [89]:
A-A[0]

array([[ 0,  0,  0,  0],
       [-1, -2,  2,  4],
       [ 3, -7,  1,  4]])

In [90]:
df=pd.DataFrame(A,columns=list('QRST'))
df-df.iloc[0]

Q  R  S  T
0  0  0  0  0
1 -1 -2  2  4
2  3 -7  1  4

In [91]:
df.subtract(df['R'],axis=0)

Q  R  S  T
0 -5  0 -6 -4
1 -4  0 -2  2
2  5  0  2  7

In [92]:
halfrow=df.iloc[0,::2]
halfrow

Q    3
S    2
Name: 0, dtype: int32

In [93]:
# Handling Missing Data 
for dtype in ['object','int']:
    print("dtype =", dtype)
    %timeit np.arange(1E6,dtype=dtype).sum()
    print()

dtype = object
48.4 ms ± 489 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

dtype = int
1.85 ms ± 31.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)



In [94]:
vals1=np.array([1,None,3,4])
vals1

array([1, None, 3, 4], dtype=object)

In [95]:
vals1.sum()

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [96]:
vals2=np.array([1,np.nan,3,4])
vals2.dtyle

AttributeError: 'numpy.ndarray' object has no attribute 'dtyle'

In [97]:
vals2.dtype

dtype('float64')

In [98]:
1+np.nan

nan

In [99]:
o*np.nan

NameError: name 'o' is not defined

In [100]:
0*np.nan

nan

In [101]:
data=pd.Series([1,np.nan,'hello',None])


In [102]:
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [103]:
data[data.notnull()]

0        1
2    hello
dtype: object

In [104]:
# droping null value
data.dropna()

0        1
2    hello
dtype: object

In [105]:
df=pd.DataFrame([[1,np.nan,2],
                [2,3,5],
                [np.nan,4,6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [106]:
# we can drop single value from Dataframe, we can only drop full rows or full column

df.dropna()

0    1  2
1  2.0  3.0  5

In [107]:
df.dropna(axis='columns')

2
0  2
1  5
2  6

In [108]:
df[3]=np.nan

In [109]:
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [110]:
df.dropna(axis='rows',thresh=3)

0    1  2   3
1  2.0  3.0  5 NaN

In [111]:
df.dropna(axis='rows',thresh=2)

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [112]:
# filling null value
data=pd.Series([1,np.nan,None,3], index=list('abcde'))
data

ValueError: Length of passed values is 4, index implies 5.

In [113]:
# filling null value
data=pd.Series([1,np.nan,2,None,3], index=list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [114]:
data.fillnan(0)

AttributeError: 'Series' object has no attribute 'fillnan'

In [115]:
data.fillna(0)

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [116]:
#forward-fill
data.fillna(method='ffill')

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [117]:
#back-fill
data.fillna(method='bfill')

a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

In [1]:
data

NameError: name 'data' is not defined

In [2]:
import numpy as np
import pandas as pd


In [3]:
vals1=np.array([1,None,3,4])
vals1

array([1, None, 3, 4], dtype=object)

In [4]:
for dtype in ['object','int']:
    print("dtype =", dtype)
    %timeit np.arange(1E6,dtype=dtype).sum()
    print()

dtype = object
47.8 ms ± 407 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

dtype = int
1.9 ms ± 38.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)



In [5]:
data=pd.Series([1,np.nan,'hello',None])
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [6]:
data[data.notnull()]

0        1
2    hello
dtype: object

In [7]:
data.dropna

<bound method Series.dropna of 0        1
1      NaN
2    hello
3     None
dtype: object>

In [8]:
data.dropna()

0        1
2    hello
dtype: object

In [9]:
df=pd.DataFrame([[1,np.nan,2],
                [2,3,5],
                [np.nan,4,6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [10]:
df.dropna()

0    1  2
1  2.0  3.0  5

In [11]:
df.dropna(axis='columns')

2
0  2
1  5
2  6

In [12]:
df[3]=np.nan
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [13]:
df.dropna(axis='columns',how='all')

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [14]:
# A multiply Index Series
# bad way ex:

index= [('Hanoi',2000),('Hanoi',2010),('HCM',2000),('HCM',2010),('Cantho',2000),('Cantho',2010),('Danang',2000),('Danang',2010)]
populations=[33871648, 37253956,
18976457, 19378102,
20851820, 25145561]
pop=pd.Series(populations,index=index)
pop

ValueError: Length of passed values is 6, index implies 8.

In [15]:
# A multiply Index Series
# bad way ex:

index= [('Hanoi',2000),('Hanoi',2010),('HCM',2000),('HCM',2010),('Danang',2000),('Danang',2010)]
populations=[33871648, 37253956,
18976457, 19378102,
20851820, 25145561]
pop=pd.Series(populations,index=index)
pop

(Hanoi, 2000)     33871648
(Hanoi, 2010)     37253956
(HCM, 2000)       18976457
(HCM, 2010)       19378102
(Danang, 2000)    20851820
(Danang, 2010)    25145561
dtype: int64

In [16]:
pop[('Hanoi',2000):('Danang',2000)]

(Hanoi, 2000)     33871648
(Hanoi, 2010)     37253956
(HCM, 2000)       18976457
(HCM, 2010)       19378102
(Danang, 2000)    20851820
dtype: int64

In [17]:
pop(for i in pop.index if i[1]==2010)

SyntaxError: invalid syntax (<ipython-input-17-b9785d46916c>, line 1)

In [18]:
pop[[i for i in pop.index if i[1]==2010]]

(Hanoi, 2010)     37253956
(HCM, 2010)       19378102
(Danang, 2010)    25145561
dtype: int64

In [19]:
pop[[i for in in pop.index if i[0]=='Hanoi']]

SyntaxError: invalid syntax (<ipython-input-19-17dd89fddbfb>, line 1)

In [20]:
pop[[i for i in pop.index if i[0]=='Hanoi']]

(Hanoi, 2000)    33871648
(Hanoi, 2010)    37253956
dtype: int64

In [21]:
# The better way: Pandas multiple index
index=pd.MultiIndex.from_tuples(index)
index

MultiIndex([( 'Hanoi', 2000),
            ( 'Hanoi', 2010),
            (   'HCM', 2000),
            (   'HCM', 2010),
            ('Danang', 2000),
            ('Danang', 2010)],
           )

In [22]:
pop.reindex(index)
pop

(Hanoi, 2000)     33871648
(Hanoi, 2010)     37253956
(HCM, 2000)       18976457
(HCM, 2010)       19378102
(Danang, 2000)    20851820
(Danang, 2010)    25145561
dtype: int64

In [23]:
pop_df=pop.unstack()

AttributeError: 'Index' object has no attribute 'remove_unused_levels'

In [24]:
pop=pop.reindex(index)

In [25]:
pop

Hanoi   2000    33871648
        2010    37253956
HCM     2000    18976457
        2010    19378102
Danang  2000    20851820
        2010    25145561
dtype: int64

In [26]:
pop[:,2010]

Hanoi     37253956
HCM       19378102
Danang    25145561
dtype: int64

In [27]:
#multiindex as extra dimension
pop_df=pop.unstack()

In [28]:
pop_df

2000      2010
Danang  20851820  25145561
HCM     18976457  19378102
Hanoi   33871648  37253956

In [29]:
pop_df.stack()

Danang  2000    20851820
        2010    25145561
HCM     2000    18976457
        2010    19378102
Hanoi   2000    33871648
        2010    37253956
dtype: int64

In [30]:
pop_df=pd.DataFrame({'total':pop, 'under18':[9267089, 9284094,
4687374, 4318033,
5906301, 6879014]})
pop_df

total  under18
Hanoi  2000  33871648  9267089
       2010  37253956  9284094
HCM    2000  18976457  4687374
       2010  19378102  4318033
Danang 2000  20851820  5906301
       2010  25145561  6879014

In [31]:
# compute the fraction of people under 18 by year

pop_under18=pop_df['under18']/pop['total']
pop_under18

KeyError: 'total'

In [32]:
# compute the fraction of people under 18 by year

pop_under18=pop_df['under18']/pop_df['total']
pop_under18|

SyntaxError: invalid syntax (<ipython-input-32-aa03b2f87906>, line 4)

In [33]:
# compute the fraction of people under 18 by year

pop_under18=pop_df['under18']/pop_df['total']
pop_under18

Hanoi   2000    0.273594
        2010    0.249211
HCM     2000    0.247010
        2010    0.222831
Danang  2000    0.283251
        2010    0.273568
dtype: float64

In [34]:
pop_under18.unstack()

2000      2010
Danang  0.283251  0.273568
HCM     0.247010  0.222831
Hanoi   0.273594  0.249211

In [35]:
df=pd.DataFrame(np.random.rand(4,2), index=[['a','a','b','b'],[1,2,1,2]],columns=['data1','data2'])
df

data1     data2
a 1  0.729763  0.715920
  2  0.022190  0.607988
b 1  0.911585  0.137840
  2  0.672803  0.719879

In [36]:
pop

Hanoi   2000    33871648
        2010    37253956
HCM     2000    18976457
        2010    19378102
Danang  2000    20851820
        2010    25145561
dtype: int64

In [37]:
pop['Hanoi',2000]

33871648

In [38]:
pop['Danang']

2000    20851820
2010    25145561
dtype: int64

In [39]:
pop.loc['Hanoi':'Danang']

UnsortedIndexError: 'Key length (1) was greater than MultiIndex lexsort depth (0)'

In [40]:
pop.loc['Hanoi':'HCM']

UnsortedIndexError: 'Key length (1) was greater than MultiIndex lexsort depth (0)'

In [41]:
pop[pop>2000000]

Hanoi   2000    33871648
        2010    37253956
HCM     2000    18976457
        2010    19378102
Danang  2000    20851820
        2010    25145561
dtype: int64

In [42]:
index=pd.MultiIndex.from_product([[2013,2014],[1,2]], names=['year','visit'])
columns=pd.MultiIndex.from_product([['Lam','Linh','Vy'],['HR','Temp']],
                                  names=['subject','type'])

In [43]:
#mock some data
data=np.round(np.random.rand(4,6),1)
data[:,::2]*=10
data+=37

In [44]:
health_data=pd.DataFrame(data,index=index,columns=columns)
heath_data

NameError: name 'heath_data' is not defined

In [45]:
health_data

subject      Lam        Linh          Vy      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      39.0  38.0  42.0  37.8  39.0  37.2
     2      44.0  37.6  41.0  37.7  43.0  37.5
2014 1      44.0  37.6  39.0  37.6  47.0  38.0
     2      38.0  37.4  39.0  37.8  38.0  37.4

In [46]:
health_data['Vy']

type          HR  Temp
year visit            
2013 1      39.0  37.2
     2      43.0  37.5
2014 1      47.0  38.0
     2      38.0  37.4

In [47]:
health_data['Lam','HR']

year  visit
2013  1        39.0
      2        44.0
2014  1        44.0
      2        38.0
Name: (Lam, HR), dtype: float64

In [48]:
health_data.iloc[:2,:2]

subject      Lam      
type          HR  Temp
year visit            
2013 1      39.0  38.0
     2      44.0  37.6

In [49]:
health_data.loc[:,('Bob','HR')]

KeyError: ('Bob', 'HR')

In [50]:
health_data.loc[:,('Lam','HR')]

year  visit
2013  1        39.0
      2        44.0
2014  1        44.0
      2        38.0
Name: (Lam, HR), dtype: float64

In [51]:
index=pd.MultiIndex.from_product([['a','c','b'],[1,2]])
data=pd.Series(np.random.rand(6),index=index)
data.index.names=['char','int']
data

char  int
a     1      0.266924
      2      0.805069
c     1      0.330929
      2      0.692709
b     1      0.701591
      2      0.040810
dtype: float64

In [52]:
try:
    data['a':'b']
except KeyError as e:
    print(type(e))
    print(e)

<class 'pandas.errors.UnsortedIndexError'>
'Key length (1) was greater than MultiIndex lexsort depth (0)'


In [53]:
data=data.sort_index()

In [54]:
data

char  int
a     1      0.266924
      2      0.805069
b     1      0.701591
      2      0.040810
c     1      0.330929
      2      0.692709
dtype: float64

In [55]:
data['a':'b']

char  int
a     1      0.266924
      2      0.805069
b     1      0.701591
      2      0.040810
dtype: float64

In [56]:
pop.unstack()

2000      2010
Danang  20851820  25145561
HCM     18976457  19378102
Hanoi   33871648  37253956

In [57]:
pop.unstack(level=0)

Danang       HCM     Hanoi
2000  20851820  18976457  33871648
2010  25145561  19378102  37253956

In [58]:
pop.unstack(level=1)

2000      2010
Danang  20851820  25145561
HCM     18976457  19378102
Hanoi   33871648  37253956

In [59]:
pop.reindex()

Hanoi   2000    33871648
        2010    37253956
HCM     2000    18976457
        2010    19378102
Danang  2000    20851820
        2010    25145561
dtype: int64

In [60]:
pop.reindex_like('Ctiy', 'Year', 'POP')

AttributeError: 'str' object has no attribute '_construct_axes_dict'

In [61]:
health_data

subject      Lam        Linh          Vy      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      39.0  38.0  42.0  37.8  39.0  37.2
     2      44.0  37.6  41.0  37.7  43.0  37.5
2014 1      44.0  37.6  39.0  37.6  47.0  38.0
     2      38.0  37.4  39.0  37.8  38.0  37.4

In [62]:
data_mean=health_data.mean(level='year')
data_mean

subject   Lam        Linh           Vy       
type       HR  Temp    HR   Temp    HR   Temp
year                                         
2013     41.5  37.8  41.5  37.75  41.0  37.35
2014     41.0  37.5  39.0  37.70  42.5  37.70

In [63]:
data_mean.mean(axis=1,level='type')

type         HR       Temp
year                      
2013  41.333333  37.633333
2014  40.833333  37.633333

In [64]:
#Combine DataSet : Concat and Append

def make_df(cols,ind):
    #quickly make a DataFrame
    data={c : [str(c) + str(i) for i in ind ]
          for c in cols}
    return pd.DataFrame(data,ind)
# Example DataFrame
make_df('ABC',range(3))

A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [65]:
df1=pd.DataFrame({'employee':['Lam','Linh','Vy','Phong'], 'group':['Accounting','Engineering','Engineering','Boss']})
df2=pd.DataFrame({'employee':['Lam','Linh','Vy','Phong'], 'hire_date':[2000,2008,2017,2020]})
print(df1);print(df2)

  employee        group
0      Lam   Accounting
1     Linh  Engineering
2       Vy  Engineering
3    Phong         Boss
  employee  hire_date
0      Lam       2000
1     Linh       2008
2       Vy       2017
3    Phong       2020


In [66]:
df3=pd.merge(df1,df2)
df3

employee        group  hire_date
0      Lam   Accounting       2000
1     Linh  Engineering       2008
2       Vy  Engineering       2017
3    Phong         Boss       2020

In [67]:
df4=pd.DataFrame({'group':['Accounting','Engineering','Engineering','Boss'],
                 'supervisor':['Nam','Sau','Quy','Thuong']})
print(df3);print(df4);print(pd.merge(df3,df4))

  employee        group  hire_date
0      Lam   Accounting       2000
1     Linh  Engineering       2008
2       Vy  Engineering       2017
3    Phong         Boss       2020
         group supervisor
0   Accounting        Nam
1  Engineering        Sau
2  Engineering        Quy
3         Boss     Thuong
  employee        group  hire_date supervisor
0      Lam   Accounting       2000        Nam
1     Linh  Engineering       2008        Sau
2     Linh  Engineering       2008        Quy
3       Vy  Engineering       2017        Sau
4       Vy  Engineering       2017        Quy
5    Phong         Boss       2020     Thuong


In [68]:
df5=pd.DataFrame({'group':['Accounting','Accounting','Engineering','Engineering','HR','HR'],
                 'skill':['math','speadsheets','coding','linux','spreadsheets','organization']})
print(df1);print(df5);print(pd.merge(df1,df5))

  employee        group
0      Lam   Accounting
1     Linh  Engineering
2       Vy  Engineering
3    Phong         Boss
         group         skill
0   Accounting          math
1   Accounting   speadsheets
2  Engineering        coding
3  Engineering         linux
4           HR  spreadsheets
5           HR  organization
  employee        group        skill
0      Lam   Accounting         math
1      Lam   Accounting  speadsheets
2     Linh  Engineering       coding
3     Linh  Engineering        linux
4       Vy  Engineering       coding
5       Vy  Engineering        linux


In [69]:
# Specification of the Merge Key

print(df1); print(df2); print(pd.merge(df1,df2,on='employee'))

  employee        group
0      Lam   Accounting
1     Linh  Engineering
2       Vy  Engineering
3    Phong         Boss
  employee  hire_date
0      Lam       2000
1     Linh       2008
2       Vy       2017
3    Phong       2020
  employee        group  hire_date
0      Lam   Accounting       2000
1     Linh  Engineering       2008
2       Vy  Engineering       2017
3    Phong         Boss       2020


In [70]:
df3=pd.DataFrame({'name':['Lam','Linh','Vy','Phong'],
                 'salary':[70000,100000,4000,900000]})
print(df1), print(df2), print(pd.merge(df1,df3,left_on="employee", right_on="name"))

  employee        group
0      Lam   Accounting
1     Linh  Engineering
2       Vy  Engineering
3    Phong         Boss
  employee  hire_date
0      Lam       2000
1     Linh       2008
2       Vy       2017
3    Phong       2020
  employee        group   name  salary
0      Lam   Accounting    Lam   70000
1     Linh  Engineering   Linh  100000
2       Vy  Engineering     Vy    4000
3    Phong         Boss  Phong  900000


(None, None, None)

In [71]:
print(df1), print(df2), print(pd.merge(df1,df3,right_on="name"))

  employee        group
0      Lam   Accounting
1     Linh  Engineering
2       Vy  Engineering
3    Phong         Boss
  employee  hire_date
0      Lam       2000
1     Linh       2008
2       Vy       2017
3    Phong       2020


TypeError: object of type 'NoneType' has no len()

In [72]:
print(df1), print(df2), print(pd.merge(df1,df3, right_on="name"))

  employee        group
0      Lam   Accounting
1     Linh  Engineering
2       Vy  Engineering
3    Phong         Boss
  employee  hire_date
0      Lam       2000
1     Linh       2008
2       Vy       2017
3    Phong       2020


TypeError: object of type 'NoneType' has no len()

In [73]:
pd.merge(df1,df3,left_on="employee",right_on="name").drop('name',axis=1)

employee        group  salary
0      Lam   Accounting   70000
1     Linh  Engineering  100000
2       Vy  Engineering    4000
3    Phong         Boss  900000

In [74]:
df6=pd.DataFrame({'name':['Peter','Paul','Mary'],
                 'food':['fish','beans','bread']},
                columns=['name','food'])
df7=pd.DataFrame({'name':['Mary','Joseph'],
                 'drink':['wine','beer']},
                columns=['name','drink'])

print(df6);print(df7);print(pd.merge(df6,df7))

    name   food
0  Peter   fish
1   Paul  beans
2   Mary  bread
     name drink
0    Mary  wine
1  Joseph  beer
   name   food drink
0  Mary  bread  wine


In [75]:
pd.merge(df6,df7, how='inner')

name   food drink
0  Mary  bread  wine

In [76]:
print(pd.merge(df6,df7, how='outer'))

     name   food drink
0   Peter   fish   NaN
1    Paul  beans   NaN
2    Mary  bread  wine
3  Joseph    NaN  beer


In [77]:
print(pd.merge(df6,df7,how='right'))

     name   food drink
0    Mary  bread  wine
1  Joseph    NaN  beer
